name: walletium
description: A new Flutter project.

publish_to: "none"

version: 1.1.0+8

environment:
  sdk: ^3.6.0-334.4.beta

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.8
  get: 4.6.6
  
  flutter_screenutil: 5.9.3
  font_awesome_flutter: 10.7.0
  google_fonts: ^6.2.1
  image_picker: 1.1.2
  carousel_slider: 5.0.0
  pin_code_fields: 8.0.1
  country_code_picker: ^3.3.0
  #firebase_crashlytics: ^3.3.4


  #  for backend
  get_storage: ^2.1.1
  logger: 2.4.0
  qr_flutter: ^4.1.0
  dotted_border: 2.1.0
  dotted_decoration: ^2.0.0
  #share_plus: 10.0.2
  cached_network_image: 3.4.1
  connectivity_plus: ^6.1.3
  flutter_spinkit: 5.2.1
  dropdown_button2: ^2.3.9
  toggle_switch: 2.3.0
  delayed_display: ^2.0.0
  flutter_svg:
  file_picker: ^8.3.5
  flutter_inappwebview: ^6.1.5
  flutter_html: ^3.0.0-alpha.6
  intl: 0.19.0
  lottie: 3.1.2

  dynamic_languages:
    git:
      url: https://github.com/appdevsx/dynamic_languages
      ref: main

  win32: ^5.10.1
  rename_app: ^1.6.2
  restart_app: ^1.3.2
  fcm_config: ^3.6.5
  firebase_core: ^3.11.0

dev_dependencies:
  flutter_launcher_icons:
  change_app_package_name: 1.3.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_launcher.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/deep_link/apple-app-site-association
    - assets/empty_animation.json
    - assets/font/
    - assets/images/
    - assets/images/bg/
    - assets/images/bg/drawer_bg.svg
    - assets/images/bg/sign-in-bg.svg
    - assets/images/others/
    - assets/images/others/confirm.svg
    - assets/images/others/congratulations.svg
    - assets/images/others/forgot-password.svg
    - assets/images/splash/
    - assets/svg/

  fonts:
    - family: Poppins-Regular
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
    - family: Roboto-Bold
      fonts:
        - asset: assets/font/Roboto-Bold.ttf
    - family: Roboto-Regular
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
